experiment_id: "f3_sintel_mmt_all_tc0.02"
dataset: "sintel"
method: "mmt"
params:
  levels: 3
  threshold_factor: 2.0
  transform_type: "mmt"
  scale_coherence: true
  color_coherence: true
  color_threshold: 0.02
  color_beta: 0.5
  eps: 0.00001
